# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.11
  - DJANGO=2.0

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
  include:
    - python: "3.6"
      env: TOXENV=quality
    - python: "3.6"
      env: TOXENV=docs

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov
